import Head from "next/head"
import Script from "next/script"
import Image from "next/image"
import { attributes, react as HomeContent } from "../content/home.md"
import styles from "../styles/Home.module.css"

const Card = (card) => (
  <a href={card.link} className={styles.card}>
    <h2>{card.title} &rarr;</h2>
    <p>{card.description}</p>
  </a>
)

export default function Home() {
  const { title, titleLink, description, descriptionCode, cards } = attributes
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Script src='https://identity.netlify.com/v1/netlify-identity-widget.js' />

      <main className={styles.main}>
        <h1 className={styles.title}>
          {title} <a href={titleLink.href}>{titleLink.name}</a>
        </h1>

        <p className={styles.description}>
          {description} <code className={styles.code}>{descriptionCode}</code>
        </p>

        <div className={styles.grid}>
          {cards && cards.map((card, k) => <Card {...card} key={k} />)}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
          target='_blank'
          rel='noopener noreferrer'
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src='/vercel.svg' alt='Vercel Logo' width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
